name: unsplash_clone
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  midtrans_sdk: ^1.0.1
  path: ^1.8.0
  provider: ^6.1.5
  shared_preferences: ^2.0.15
  supabase_flutter: ^2.9.0
  http: ^0.13.6
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
