name: unsplash_clone
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  http: ^1.5.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  midtrans_sdk: ^1.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  slide_to_act: ^2.0.2
  supabase_flutter: ^2.9.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
